// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieApp_kncook.Models;

namespace MovieApp_kncook.Migrations
{
    [DbContext(typeof(MovieEntriesContext))]
    partial class MovieEntriesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("MovieApp_kncook.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ApplicationId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            ApplicationId = 1,
                            Category = "Comedy",
                            Director = "Ben Stiller",
                            Edited = true,
                            LentTo = "Luke",
                            Note = "so funny",
                            Rating = "PG13",
                            Title = "Zoolander"
                        },
                        new
                        {
                            ApplicationId = 2,
                            Category = "Drama/Adventure",
                            Director = "Mitch Davis",
                            Edited = false,
                            LentTo = "church",
                            Note = "inspirational",
                            Rating = "PG",
                            Title = "The Other Side of Heaven"
                        },
                        new
                        {
                            ApplicationId = 3,
                            Category = "Romance/Comedy",
                            Director = "Anne Fletcher",
                            Edited = true,
                            LentTo = "Katherine",
                            Note = "My favorite movie",
                            Rating = "PG13",
                            Title = "The Proposal"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
